spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: my-secret-pw
  jpa:
    generate-ddl: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      app: simple-jpa-maven
      env: dev
